### PR TITLE
Modified master

### PR DESCRIPTION
**Pull request by Engerrs**
Hi @martinburchell ,
I made some fixes for pep8 and added 'syndicate' command in order to trigger syndication for one or all Datasets on the portal.

### CODE REVIEW

**Comment by Engerrs** [comment]
Added more updates for logging.
Updated naming creation process as there been an issue with that added "-" at the start of each name when syndication prefix is not set up.
Updated "update_dataset_for_syndication" action by adding "package_id" as extra key in it, so it easy to find package while making updates to it.

**Comment by Engerrs** [comment]
Added **ISyndication** interface to replace the current action **update_dataset_for_syndication**.
Updated Readme by adding **Syndication Hooks** topic to specify its purpose.

**Comment by martinburchell** [comment]
Thanks for these. These look like useful changes and I'll have a look at them when I have the time.

With the change to replace the action with the interface, is this just a stylistic change to a CKAN-preferred way of doing things or are there problems with using the plugin on more recent versions of CKAN? See https://github.com/aptivate/ckanext-syndicate/issues/7

**Comment by Engerrs** [comment]
Hi @martinburchell 
I didn't face any problems with using the plugin on more recent versions of CKAN.
Nevertheless, **Interfaces** are playing a role of hooks in CKAN and because we actually updating the **package** before the create/update action if more of a hook rather then just an action.

It's also easier form the user perspective, as to add actions we need to add the IActions interface in order to register our actions, while it's more easier to import Syndicate Interface itself.

**Comment by Engerrs** [comment]
Hi @martinburchell 
I added an Multiple Syndication Profiles feature https://github.com/aptivate/ckanext-syndicate/pull/9/commits/08d9389e839af71b3ae76ab03a1a5182c7d81f5a, updated the README file.
I won't effect the current implementation.
Tested it on CKAN 2.7.

I'm planning to add one more commit to update Syndication to use the new CKAN worker(RQ) and still be able to use Celery for old CKAN versions.

**Comment by Engerrs** [comment]
Hi @martinburchell 
I updated Syndication so it can work with both Celery and RQ workers.
The solution mentioned here https://docs.ckan.org/en/2.8/maintaining/background-tasks.html#supporting-both-systems-at-once

**Pull request closed without merging**
